apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booking-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: booking-api.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booking-api-service
            port:
              number: 80
